### GENERAL SETTINGS ###

# Site settings
title: Pawlik Brillenmode, Inh. Oliver Krech
description: "Den Durchblick bekommen"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  services:
    output: true
    permalink: /services/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Hindenburgstr. 5A
    - 37441 Bad Sachsa

email: hello@optikrech.de

telefon: +49 555 123456

# Öffnungszeiten (add as many lines as necessary). Shown in footer and on Contact page.
businesshours:
  - lines:
    - Mo.- Fr. 8:30 - 13:00, 14:30 - 18:00
    - Sa. 9:00 - 13:00
    
# Erreichbarkeit. Shown in footer and on Contact page.
contact:
  - lines:
    - Tel. 05523 - 93006

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Oliver Krech
    position: Augenoptikermeister
    text: 
    img: team01.jpg
    # Wenn Anzeige eines Overlays mit Email Möglichkeit, dann nachfolgende Zeilen wieder aktivieren
    #social:
      #- title: envelope #use for email address
       # url: mailto:name@domain.com
  - name: XXX
    position: Augenoptikerin
    text: 
    img: team03.jpg
  - name: XXX
    position: Praktikant
    text: 
    img: team04.jpg

# Marken Informationen. Auf Home und About pages.
marken:
  - name: Ray Ban
    img: rayban.jpg
  - name: Rodenstock
    img: rodenstock.jpg
  - name: Timberland
    img: timberland.jpg
  - name: Bogner
    img: bogner.jpg

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Der beste Optiker den man sich wünschen kann. Ein Fachmann auf seinem Gebiet. Es hat nie einen kompetenteren Optiker gegeben."
    author: Jacqueline Krech
    position: WEB DESIGNER - jkrech.de
